### ISSUE TITLE
Replace /doc command with an inline mode bot

### ISSUE THREAD

**Issue by upsuper** [upsuper/telegram-rustevalbot#50]

**Comment by upsuper** [comment]
To implement this, we need to have a new top level mod `rustdoc`, and move majority of code in `eval::command::doc` into that mod.

**Comment by huangjj27** [comment]
Hi @upsuper, I'm trying to compile your bot on Windows, but it seems can't compile `signal-hook v0.1.6`. Do I have to refactor the bot on LInux?

**Comment by huangjj27** [comment]
- [ ] move out the doc command
- [ ] refactor bot
- [ ] write documents
